{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agile-retro.fullname" . }}-postgres
  labels:
    {{- include "agile-retro.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "agile-retro.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
