{{- if and .Values.postgresql.enabled (not .Values.sqlite.enabled) .Values.postgresql.persistence.enabled (not .Values.postgresql.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agile-retro.fullname" . }}-postgres
  labels:
    {{- include "agile-retro.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}
  {{- if .Values.postgresql.persistence.storageClassName }}
  storageClassName: {{ .Values.postgresql.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
