import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

// Self-hosted Geist fonts (OFL licensed) so the build never reaches out to
// fonts.googleapis.com — required for airgapped / TLS-proxied office networks.
// The .woff2 files are variable fonts covering weights 100–900.
const geistSans = localFont({
  src: [{ path: "./fonts/geist-sans-latin.woff2", weight: "100 900", style: "normal" }],
  variable: "--font-geist-sans",
  display: "swap",
});

const geistMono = localFont({
  src: [{ path: "./fonts/geist-mono-latin.woff2", weight: "100 900", style: "normal" }],
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { auth } from "@/auth"
import { ClientLayout } from "@/components/ClientLayout"

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ClientLayout 
              session={session} 
              keycloakIssuer={process.env.AUTH_KEYCLOAK_ISSUER}
            >
              {children}
            </ClientLayout>
          </ThemeProvider>
      </body>
    </html>
  );
}
